import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-row min-h-screen relative">
        <Sidebar className="w-80 fixed h-screen" />
        <main className="flex-1 ml-80">{children}</main>
      </body>
    </html>
  );
}
